filebeat.prospectors:
- input_type: log
  paths:
    - /datain/irc/*.txt
  document_type: log
#  encoding: euc-jp
  close_*: 5m
  harvester_limit: 600 # parallel open file-handles
  

#- input_type: log
#  paths:
#    - c:\Users\Lukas\AppData\Roaming\X-Chat 2\xchatlogs\IRC Kyoto-#example.log
    
#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["logstash:5043"]

