version: '3'
services:
  web:
    build: 
        context: ./howler/
        dockerfile: Dockerfile
    links:
     -  database
    hostname: web
    ports:
     - "80:80"
    network_mode: bridge
  
  database:
    build:
        context: ./db/
        dockerfile: Dockerfile
    ports: 
     - "5432:5432"
    network_mode: bridge
    env_file:
     - ./db/database.env
    volumes:
     - ./data/database:/var/lib/postgresql/data/pgdata
