version: '3'
services:
  web:
    build: 
        context: ./howler/
        dockerfile: Dockerfile
    links:
     - database
     - elasticsearch
    hostname: web
    ports:
     - "80:80"
    network_mode: bridge
  
  database:
    build:
        context: ./db/
        dockerfile: Dockerfile
    ports: 
     - "5432:5432"
    network_mode: bridge
    env_file:
     - ./db/database.env
    volumes:
     - ./data/database:/var/lib/postgresql/data/pgdata

  elasticsearch:
    build:
        context: ./elasticsearch/
        dockerfile: Dockerfile
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:
     - discovery.type=single-node
    hostname: elasticsearch
    network_mode: bridge
  
  importer:
    build:
       context: ./importer/
       dockerfile: Dockerfile
    links:
     - elasticsearch
    volumes:
     - ./datain:/datain
    hostname: importer
    network_mode: bridge

  logstash:
    build:
       context: ./logstash/
       dockerfile: Dockerfile
    ports:
     - "5043:5043"
    hostname: logstash
    network_mode: bridge
    links:
     - elasticsearch
  
  filebeat:
    build:
      context: ./filebeat/
      dockerfile: Dockerfile
    hostname: filebeat
    network_mode: bridge
    links:
     - logstash
    volumes:
     - ./datain:/datain

  kibana:
    build:
      context: ./kibana/
      dockerfile: Dockerfile
    ports:
      - "5601:5601"
    hostname: kibana
    network_mode: bridge
    links:
      - elasticsearch

