# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonym',
            name='synonym_term_b_katakana',
            field=models.CharField(default='', max_length=200, verbose_name='Synonym Term B Katakana'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='synonym_term_a',
            field=models.CharField(max_length=200, verbose_name='Synonym Term A'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='synonym_term_b',
            field=models.CharField(max_length=200, verbose_name='Synonym Term B (shortcut)'),
        ),
    ]
