# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20161213_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synonym',
            name='synonym_term_b',
            field=models.CharField(max_length=200, verbose_name='Synonym Term B - shortcut'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='synonym_term_b_katakana',
            field=models.CharField(blank=True, default='', help_text='If provided, term will be added to userdict (Required if shortcut)', max_length=200, verbose_name='Synonym Term B Katakana'),
        ),
    ]
