# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym_term_a', models.CharField(max_length=200)),
                ('synonym_term_b', models.CharField(max_length=200)),
            ],
        ),
    ]
